services:
    ganstaz.esffs.listener:
        class: ganstaz\esffs\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
